version: '3'

services:
  e2e:
    container_name: cypress
    build: .
    command: >
      bash -c "cd cypress &&
        npx cypress run -s cypress/integration/examples/*.js"
    volumes:
      - ./:/cypress