const dispenserData = {
<<<<<<< HEAD
	shippingAdderss: 'Testing Zone Street-01 Alabama',
	changedShippingAdderss: 'QA Testing platform Street-11 Alabama',
	billingAdderss: 'Testers Place, Street-02, Alabama Town',
	zipCode: '34231',
	billingZipCode: '52345',
	cityName: 'Alabama',
	changedCityName: 'Alaska',
	orderDetailsTitle: 'Prescription & Order Details',
	editButtonName: 'Edit Contents',
	addingProduct: 'Add Product',
	closeButton: 'Close',
	dismissButton: 'Dismiss',
	selectOptionType: 'Select...',
	prescriptionAndOrderDetailsPage: 'Prescription & Order Details',
	notesMessage: 'This order is created by the hub dispenser/standard dispenser you have to approve it.',
	instructionMessage: 'Follow these instructions.',
=======
	dispenserUrl: '/dispenser',
	orderPageUrl: '/orders',
	addPayments: 'Missing Payment Method ',
	shippingAdderss: 'Testing Zone Street-01 Alabama',
	changedShippingAdderss: 'QA Testing platform Street-11 Alabama',
	billingAdderss: 'Testers Place, Street-02, Alabama Town',
	dispenserPatientName: 'Qa Dispenser Patient',
	zipCode: '34231',
	changedZipCode: '67890',
	billingZipCode: '52345',
	cityName: 'Alabama',
	changedCityName: 'Alaska',
	newDispenserName: 'Adriel Kuhn',
	hubDispenserEmail1: 'ibis+hub@droicelabs.com',
	hubDispenserEmail2: 'ibis+hub2@droicelabs.com',
	newStanDispenserEmail: 'ibis+rx2@droicelabs.com',
	hubDispenserEmail11: 'ibis+hub11@droicelabs.com',
	hubDispenserEmail12: 'ibis+hub12@droicelabs.com',
	hubDispenserEmail13: 'ibis+hub13@droicelabs.com',
	hubDispenserEmail14: 'ibis+hub14@droicelabs.com',
	dispenserLoginpageName: 'Dispenser Portal',
	stdPatientEmailName: 'qadispenserpatient01',
	addPayments: 'Missing Payment Method ',
	orderDetailsTitle: 'Prescription & Order Details',
	editButtonName: 'Edit Contents',
	paymentOption: 'Provide Payment',
	paymentUrl: '/payment',
	paymentPageName: 'Step 2: Payment & Shipping',
	recieptData: 'Print Receipt',
	orderStatus: 'Awaiting Shipping Details',
	orderStatus1: 'Transferred',
	postageLabel: 'Create Postage Label',
	parcelType: 'Standard LegrandeRx Bubble Mailer',
	finalPageName: 'Step 3: Review & Submit',
	successMessage: 'Order has been successfully updated.',
	addingProduct: 'Add Product',
	closeButton: 'Close',
	Createorderbutton: 'Create an Order for this Patient',
	dismissButton: 'Dismiss',
	selectOptionType: 'Select...',
	selectOptionType2: 'Select a type',
	OrderButton: 'Update Order',
	retailDispensername: 'Retail Dispenser',
	compoundDispensername: '503a Compound',
	RX_DispenserName: 'RX Dispenser',
	contentValue: '1',
	changedContentValue: '2',
	randomPrice: '4000',
	createOrderName: 'Create Order',
	approveOrderMessage: 'Please confirm that you approve the selected prescriptions.',
	contactUsName: 'Contact Us',
	companyMail: 'support@legranderx.com',
	companyPhoneNumber: '(714) 243-8373',
	accountNumber: '9867601024476',
	PCNnumber: '867024476',
	RxBinNumber: '5624476',
	groupNumber: '67624476',
	productTypeOption: 'All',
	productTypeOptionName: 'Rx Medications',
	prescriptionAndOrderDetailsPage: 'Prescription & Order Details',
	pendingOrderStatus: 'Pending',
	canceledOrderStatus: 'Canceled',
	orderText: 'Order',
	electronicSignatureText: 'Electronically Signed By:',
	orderDateRawName: 'Order Date',
	statusText: 'Status',
	emailColumnName: 'Email Address',
	createRxOrderPageName: ' Step 1: Create your Rx',
	cancelOrderMessage: 'Are you sure you want to cancel this order?',
	filterOrderName: 'Filter Orders',
	notesMessage: 'This order is created by the hub dispenser/standard dispenser you have to approve it.',
	secondNotesMessage: 'This is another notes, that describe that order is create by the hub dispenser.',
	editMessage: 'Congratulations, you have successfully edited this account.',
	editRXPageName: 'Edit Rx Order',
	emptyPageText1: ', simply search above, select a product, and add it.',
	emptyPageText: 'Once added, you will be able to adjust details for any given product. You will also be able to add use instructions for each product.',
	createPostageTextName: 'Create Postage Label',
	noButtonName: 'No',
	mailOrderTextMessage: 'Thank you for your order!',
	mailOrderText: 'Order #',
	viewOrderDetailButton: 'View Order Details',
	noReplyMail: 'noreply@legranderx.com',
	copyRightText: 'Copyright © Legrande Corp.',
	copyRightText2: ' All rights reserved',
	confirmationMailHeading: 'Legrande Order Confirmation',
	invalidDispenserEmail: 'stddispenseradmin@getnada.com',
	noDispenserMessage: 'There is no dispenser with this login',
	messagePageUrl: 'https://getnada.com/msg',
	instructionMessage: 'follow these instructions.',
	dispenserUpdationMessage: 'Congratulations. You have successfully updated the dispenser account.',
	yopmailTabName: '[SPAM]Legrande',
	prescriptionOnFileText: 'Prescription on File',
	completeButtonName: 'Complete',
	pharmacistTypeUser: 'Pharmacist',
	technicianTypeUser: 'Technician',
	activeStatus: 'Active',
	suspendedStatus: 'Suspend',
	profileUpdationMessage: 'Congratulations. You have successfully updated this user\'s profile.',
	updateProductStatement1: 'If you wish to change the price of this item, please be aware that the new amount will not be applied to any orders that are currently part of a treatment plan for 30 days. After 30 days, the new price will be used for all new and existing orders.',
	updateProductStatement2: 'Any patients presently receiving this item as part of a treatment plan will be notified by email of the price change and will have a 30-day window to cancel or edit their treatment plan before the new pricing goes into effect',
	compoundProductPriceUpdateMessage: 'You have successfully updated the price of Product_Compound',
	rxProductPriceUpdateMessage: 'You have successfully updated the price of Product_Rx',
	OTCProductUpdationMessage: 'You have successfully updated the price of Product_OTC',
	createOrderMessage: 'Order has been created successfully',
	removeGroupMessage: 'Are you sure you would like to remove this group from the plan?',
	PyorName: 'Max Life',
>>>>>>> origin/master
	PayorAccNo: '5616548461611',
	PayorGroupNo: '61616515616',
	PayorRX_binNo: '41486516165',
	PayorPCnNo: '66463116166',
	yesbutton: 'Yes',
<<<<<<< HEAD
=======
	PickUpPerson: 'Pick Up In Person',
	CourierService: 'Courier Service',
>>>>>>> origin/master
	patientTab: 'Patients',
	printLabel: 'Print Postage Label',
	CompleteOrderNotes: 'Patient Complete The Treatment',
	CancelOrderNotes: 'Patient Cancel The Treatment',
	OutofNetworkOrderNotes: 'Order Go To Out Network',
	patient: '{downarrow}{enter}',
	OutofNetworkOrder: 'Send out of Network',
<<<<<<< HEAD
=======
	PrintReceipt: 'Print Receipt',
	filter: 'Filters',
	OrderStatusFilter: 'Order Status',
	EnRoute: 'En Route',
	SubscriptionCadence:"Delivered every 3 months",
>>>>>>> origin/master
};

// export the users you created so you can import them in your tests
export { dispenserData };