const dispenserData = {
	shippingAdderss: 'Testing Zone Street-01 Alabama',
	changedShippingAdderss: 'QA Testing platform Street-11 Alabama',
	billingAdderss: 'Testers Place, Street-02, Alabama Town',
	zipCode: '34231',
	billingZipCode: '52345',
	cityName: 'Alabama',
	changedCityName: 'Alaska',
	orderDetailsTitle: 'Prescription & Order Details',
	editButtonName: 'Edit Contents',
	addingProduct: 'Add Product',
	closeButton: 'Close',
	dismissButton: 'Dismiss',
	selectOptionType: 'Select...',
	prescriptionAndOrderDetailsPage: 'Prescription & Order Details',
	notesMessage: 'This order is created by the hub dispenser/standard dispenser you have to approve it.',
	instructionMessage: 'Follow these instructions.',
	PayorAccNo: '5616548461611',
	PayorGroupNo: '61616515616',
	PayorRX_binNo: '41486516165',
	PayorPCnNo: '66463116166',
	yesbutton: 'Yes',
	patientTab: 'Patients',
	printLabel: 'Print Postage Label',
	CompleteOrderNotes: 'Patient Complete The Treatment',
	CancelOrderNotes: 'Patient Cancel The Treatment',
	OutofNetworkOrderNotes: 'Order Go To Out Network',
	patient: '{downarrow}{enter}',
	OutofNetworkOrder: 'Send out of Network',
};

// export the users you created so you can import them in your tests
export { dispenserData };