const masterCreationData = {
	addProduct: 'Add New Product',
	productRxName: '100 Rx',
	masterUrl: '/master',
	RequiredFieldAlert: 'Required field',
	PaymentRequiredAlert: 'REQUIRED FIELD',
	RequiredSelection: 'REQUIRED SELECTION',
	invalidEmailAlert: 'Invalid Email Address',
	InvalidCredencial: 'Invalid credentials',
	Gmv: '22',
	categoryRxName: 'Category_Rx',
	manufacturerRxName: 'Manufacturer_Rx',
	AWP_Number: '1234',
	ARP_Number: '12345',
	NDC_Number: '54321',
	PN_Number: '121212',
	Package_Size: '80',
	Rx_Price: '90',
	PasswordConfirmation: "Password set successfully",
	OTC_Price: '50',
	category_Compound_Name: 'Category_Compound',
	manufacturer_Compound_Name: 'Manufacturer_Compound',
	Compound_Price: '70',
	Reseller_License_Number: '123456789',
	Group_NPI_Number: '7890987',
	dispensersCreationMessage: 'Congratulations. You have successfully created a new dispenser account. The Master Admin will receive an Email invitation to Register.',
	practiceCreationMessage: 'Congratulations. You have successfully created a new practice account. The Master Admin will receive an Email invitation to Register.',
	practiceDashBoard: 'Practices',
	userDashBoard: 'Users',
	PayorDashboard: 'Payors & Coupons',
	dispenserDashboard: 'Dispensers',
	productDashBoard: 'Products',
	myDashBoard: 'My Dashboard',
	orderVerifyStatus: 'Open',
	successfulOrderApproval: 'You have successfully approved the selected prescriptions!',
	requiredField: 'Required field',
	inValidPassword: 'Password1',
	SubmitId: 'Submit',
	AddRX: 'Add Product',
	dispenser: 'Dispenser',
};

// export the users you created so you can import them in your tests
export { masterCreationData };