const masterCreationData = {
	addProduct: 'Add New Product',
	addDispenser: 'Add New Dispenser',
	productRxName: '100 Rx',
	masterUrl: '/master',
	masterDispenserUrl: '/master/dispensers',
	masterPracticeUrl: '/practices',
	masterUsersUrl: '/master/users',
	masterPayorUrl: '/master/payors-and-coupons',

	RequiredFieldAlert: 'Required field',
	PaymentRequiredAlert: 'REQUIRED FIELD',
	RequiredSelection: 'REQUIRED SELECTION',
	invalidEmailAlert: 'Invalid Email Address',
	InvalidCredencial: 'Invalid credentials',
	InvalidNumberAlert: 'Invalid Number',
	SafeText: 'Safe text required',

	masterEmail: 'master@legranderx.com',
	Gmv: '22',
	accountCreationMasterEmail: 'master@legranderx.com',
	MasterTestEmail: 'master2@legranderx.com',
	MasterTestEmail2: 'master4@legranderx.com',
	categoryRxName: 'Category_Rx',
	manufacturerRxName: 'Manufacturer_Rx',
	AWP_Number: '1234',
	ARP_Number: '12345',
	NDC_Number: '54321',
	PN_Number: '121212',
	Package_Size: '80',
	Rx_Price: '90',
	changedPriceRate: '100',
	product_OTC_Name: 'Product_OTC',
	category_OTC_Name: 'Category_OTC',
	manufacturer_OTC_Name: 'Manufacturer_OTC',
	PasswordConfirmation: "Password set successfully",
	OTC_Price: '50',
	product_Compound_Name: 'Product_Compound',
	category_Compound_Name: 'Category_Compound',
	manufacturer_Compound_Name: 'Manufacturer_Compound',
	Compound_Price: '70',
	dispenserLink: 'Dispensers',
	Reseller_License_Number: '123456789',
	Group_NPI_Number: '7890987',
	productAddSuccessFullMessage1: 'You have successfully added Product_Rx.',
	productAddSuccessFullMessage2: 'You have successfully added Product_OTC.',
	productAddSuccessFullMessage3: 'You have successfully added Product_Compound.',
	updationSuccessFullMessage1: 'You have successfully updated Product_Rx.',
	updationSuccessFullMessage2: 'You have successfully updated Product_OTC.',
	updationSuccessFullMessage3: 'You have successfully updated Product_Compound.',
	dispensersCreationMessage: 'Congratulations. You have successfully created a new dispenser account. The Master Admin will receive an Email invitation to Register.',
	practiceCreationMessage: 'Congratulations. You have successfully created a new practice account. The Master Admin will receive an Email invitation to Register.',
	userCreationMessage: 'Congratulations. You have successfully created new user profile.',
	practiceDashBoard: 'Practices',
	userDashBoard: 'Users',
	userAdd: 'Add New User',
	userDispenser: 'Actos',
	userPractice: 'Diza Practice',
	PayorDashboard: 'Payors & Coupons',
	editText: 'Edit',
	productText: 'Product',
	dispenserDashboard: 'Dispensers',
	productDetailRequiredText: 'Product Details (Required):',
	productDashBoard: 'Products',
	myDashBoard: 'My Dashboard',
	removeTemplateMessage: 'Are you sure you want to remove this',
	orderVerifyStatus: 'Open',
	successfulOrderApproval: 'You have successfully approved the selected prescriptions!',
	productDescription: 'This product is made by the dispenser account',
	requiredField: 'Required field',
	invalidEmailText: 'Invalid Email Address',
	atLeastCharacter: 'At least 8 characters required.',
	passwordFieldMessage: 'Password must contain: an uppercase letter, a number AND a special character (!, @, #, etc.)',
	unAuthorizedText: 'Unauthorized',
	invalidEmailId: 'master+salegranderx.com',
	inValidPassword: 'Password1',
	halfPassword: 'Password',
	noMasterMessage: 'There is no master with this login',
	adminTabMessage: 'User has not accepted their registration invite',
	inviteMessageSent: 'The invite has been sent.',
	oCuSoftText: 'OCuSoft',
	SubmitId: 'Submit',
	AddRX: 'Add Product',
	PracticeUser: '/practice/users',
	dispenser: 'Dispenser',
	practicetype: 'Practice'
};

// export the users you created so you can import them in your tests
export { masterCreationData };