const PatientData = {

    InsurancePagetext: 'Please tell us about your health insurance.',
    ConfirmAllSet: "Your email address has been verified, and your registration is complete.",
    ConfirmComplete: 'Complete Account Set',
    VerifyProduct: 'Welcome to Legrande Health!',
    OrderDashboard: 'Hi',
    AccountLink: 'Account',
    AccountInfo: 'View your contact and payment information.',
    PasswordLink: 'Password',
    PasswordInfo: 'Update your current sign-in password.',
    PreferenceLink: 'Preferences',
    PreferenceInfo: 'Adjust account and notification settings',
    ContactDetails: 'Contact Details',
    PaymentMethod: 'Payment Method',
    BillingAddress: 'Billing Address',
    ShippingAddress: 'Shipping Address',
    Changepassword: 'Change password',
    UpdateButton: 'Update',
    CancelButton: 'Cancel',
    TextMessages: 'Text Messages',
    Messagedetails: 'Receive order updates by text message in addition to email.',
    AdditionalMessages: 'Additional Messages',
    additionaldetails: 'Receive savings and educational messages from Legrande Health.',
    BackToDashboard: 'Order Details',
    Total: 'Total',
    Resetconfirm: 'Password Email Sent.',
    Donebutton: 'Done',
    PlanCanceled: 'Your plan has been canceled.',
    ThankyouMessage: 'Thank you for your feedback!',
    HomeNotification: "We just need a few more details from you, then we'll be ready to ship!",
    OrderSubmited: 'Your order has been submitted',
    CustomReason: 'I have completed my treatment.',
    CustomReason: 'I have completed my treatment',
    Verifyforgetmail: 'Set New Password for Legrande Account',
    SignIn: 'Sign In',
    CheckDetailsPending: "You’re all caught up!,We'll let you know as soon as anything changes."
}
export { PatientData }
