
const practiceData = {
<<<<<<< HEAD
	addPatientLink: 'Create New Patient',
	createAccount: 'Create Account',
	Rx_productType: 'RX',
	OTC_productType: 'OTC',
	Compound_productType: 'Compound',
	paymentButtonName: 'Skip Payment',
	SelectButton: 'Select',
	continueButton: 'Continue',
	buttonTag: 'button',
	SaveandExitbutton: 'Save and Exit',
	creditCardNumber: '02a600c0170018008292;542418******1765=3406?*89b080e99b450a0c0523757a5c28d6939c12f8519509d1ac000000000000000000000000000000000000000030343952303337373034ffff98765400068000271a4203',
	CardNumber: '5555 5537 5304 8194',
	nameOnCard: 'Adma Zampa',
	cardSecurityPin: '123',
	ViewDetailsOfOrder: 'View Details',
	DropchartTitle1: 'Welcome Letter',
	DropchartTitle2: 'Patient Directions',
	invalidPhoneNumberMessage: 'Invalid phone number',
=======
	practiceUrl: '/practice',
	practiceUrlofAddnewOrder: '/practice/orders/new',
	addRX: 'Create Rx',
	createNewRxButtonName: 'Create New Rx',
	CreateCustomPlan: 'Create Custom Plan',
	patientName: 'Alisha Daniel',
	testPatientName: 'Qa Patient',
	patient2Name: 'QAPatient Patient',
	Patient01Name: 'Patient 01',
	patient01Email: 'patient01@getnada.com',
	newPracticerEmail: 'qasapractice01@getnada.com',
	addNamePracticer: 'qasapractice01',
	addPatientLink: 'Create New Patient',
	createAccount: 'Create Account',
	accountCreationMessage: 'Congratulations, you have successfully created a new Patient Account.',
	orderUpdatedMessage: 'Order has been successfully updated.',
	orderTransferredMessage: 'This order has been successfully transferred',
	searchField: 'Search by Name',
	doctorName: 'Diza Practice',
	doctor2Name: 'Practice Admin 2',
	practiceAdminDoctor: 'Practice Admin',
	techDoctorName: 'Practice 2 Admin',
	mailSentConfirmation: 'An email confirmation has been sent to the patient.',
	Rx_productType: 'RX',
	OTC_productType: 'OTC',
	Compound_productType: 'Compound',
	productName: 'Test VP',
	reviewUrl: 'orders/new/review',
	paymentButtonName: 'Skip Payment',
	SelectButton: 'Select',
	nextButtonName: 'Next',
	continueButton: 'Continue',
	buttonTag: 'button',
	SaveandExitbutton: 'Save and Exit',
	paymentPageUrl: '/orders/new/payment',
	creditCardNumber: '02a600c0170018008292;542418******1765=3406?*89b080e99b450a0c0523757a5c28d6939c12f8519509d1ac000000000000000000000000000000000000000030343952303337373034ffff98765400068000271a4203',
	CardNumber: '5555 5537 5304 8194',
	invalidCreditCardNumber: '4000100015610024',
	cardDetails: 'ending in 2224',
	nameOnCard: 'Adma Zampa',
	cardSecurityPin: '123',
	cardType: 'Visa',
	findPatient: 'Find a Patient',
	findPatientName: 'Adrien Schaefer',
	ViewDetailsOfOrder: 'View Details',
	templateUrl: '/templates',
	templateType: 'Individual Orders',
	templateTypeTreatment: 'Treatment Plans',
	treatementPlanText: 'Treatment Plan',
	templateOptionType: 'All Templates',
	DropchartTitle1: 'Welcome Letter',
	DropchartTitle2: 'Patient Directions',
	cancelOrderMessage: 'Are you sure you want to cancel?',
	cancelOrderMessage_2: 'Any changes will be lost.',
	message: 'Hey,I need your help. Please help me',
	providePaymentName: 'Provide Payment',
	productPageUrl: '/products',
	productListName: 'Product List',
	productListWithQuantity: 'Product List (10 Results)',
	productColumnName: 'Drug Name & Form',
	manufacturarColumnName: 'Mfg.',
	productTypeColumnName: 'Type',
	productCategoryColumnName: 'Category',
	nameColumn: 'Name',
	DOBcolumn: 'DOB',
	emailColumn: 'Email Address',
	sizeTextName: 'Size',
	phoneColumn: 'Phone',
	planColumnName: 'Tx Plan',
	patientSearchTabName: 'New Patient',
	newAccountText: 'Patient Account',
	requiredText: 'Patient Details (Required):',
	patientRawName: 'Patient Name',
	forgetPasswordPopUpMessage: 'Please enter the email address associated with your account. We’ll send you an email with your username and a link to reset your password.',
	forgetPasswordMessage: 'If you still need help, please',
	fogetPasswordPageName: 'Password Reset',
	allergiesMessage: 'To add a known patient allergy, simply type the name of the allergy into the field and press return after each entry.',
	accountSettingText: 'Account Settings',
	clearTextName: 'Clear',
	TemplateCancelMessage1: 'Are you sure you want to leave this page?',
	TemplateCancelMessage2: 'Any unsaved changes will be lost.',
	financingOption: 'Finance',
	qaTechnicianName: 'Practice 2 Technician',
	qaTechnicianMail: 'ibis+practice2tech@droicelabs.com',
	inValidPracticeEmail: 'qasapracticeadmin@getnada.com',
	noPracticeMessage: 'There is no practice with this login',
	invalidPhoneNumberMessage: 'Invalid phone number',
	safeStringMessage: 'Safe string required',
	invalidFormatAddress: 'Testing Zone Street-01, @!@ @!@! Alabama',
	practicerUpdateMessage: 'Congratulations. You have successfully updated the practice account.',
	changeAdminMessage: 'Are you sure you want to remove the current Master Admin and assign a new one?',
	newAdminSuccessfulMessage: 'Congratulations, you have successfully assigned a new Master Admin. The previous Master Admin\'s account will be suspended. The new Master Admin can un-suspend the account as a regular user if they wish.',
	adminPageName: 'Master Admin',
	finalOrderUpdateMessage: 'Order successfully updated.',
>>>>>>> origin/master
	patientApprovalButton: 'Confirm Approval',
	transferOrderButton: 'Transfer Order',
};
// export the users you created so you can import them in your tests
export { practiceData };