name: GitHub Actions Demo
on: [push]
jobs:
 cypress-test:
    runs-on: ubuntu-latest
    container: cypress/base:14.19.0
    steps: 
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        run: npm install --dev
        run: npm run record-test