name: GitHub Actions Demo
on: 
  push:
    branches:
      - 'master'

jobs:
 cypress-test:
  name: run on linux
  runs-on: ubuntu-latest
  container: cypress/base:14.19.0
    steps: 
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install
          npm install --dev
          npm run record-test