name: Legrande GitHub Actions
on:
  # schedule:
  # - cron: "0 0 * * *"

  push:
    branches:
      - 'master'
    
# env: 
#   CYPRESS_CACHE_FOLDER: cypress/cache
  
jobs:
 cypress-test:
  name: Run on windows
  runs-on: ubuntu-20.04
  steps: 
    - uses: actions/checkout@v2

    # - name: Cache Node Modules
    #   id: cache-node-modules
    #   uses: actions/cache@v2
    #   with:
    #     path: node_modules
    #     key: node-modules-${{ hashFiles('package-lock.json') }}

    # - name: Cache Cypress Binary
    #   id: cache-cypress-binary
    #   uses: actions/cache@v2
    #   with:
    #     path: cypress/cache
    #     key: cypress-binary-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      # if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        npm install
        npm install --dev

    - uses: cypress-io/github-action@v2
      continue-on-error: true
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}