name: Run every end of the day
on:
  schedule:
  - cron: "0 0 * * *"

name: GitHub Actions Demo
on: 
  push:
    branches:
      - 'master'

jobs:
 cypress-test:
  name: run on windows
  runs-on: windows-latest
  steps: 
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm install --dev
        npm run record-test

    - name: Copy execution test screenshots
      run: |
        mkdir Reports
        cp -r cypress/screenshots Reports/screenshots
    
    - name: merge test reports
      run: merge:reports

    - name: Generate HTML reports
      run: create:html:report
